[package]
name = "mlprofiler"
version = "0.1.0"
authors = ["Gabriel Majeri <gabriel.majeri6@gmail.com>"]
edition = "2018"

[dependencies]
nix = "0.17"

[patch.crates-io]
nix = { git = "https://github.com/GabrielMajeri/nix", branch = "ptrace-interrupt" }
